### PR TITLE
HG-152 - added deployment scripts, re-added yarn scripts, added some documentation, and cleaned out an unused file

### LINKED ISSUE #152: re-add removed package.json scripts to control pm2 and add image optimization and fix hmr
hmr - hot module reloading, auto reloads page in browser on code change
pm2 - runs package.json scripts as daemon

image optimization using vite - https://github.com/FatehAK/vite-plugin-image-optimizer

### PR DESCRIPTION
**Pull request by zach2825**
Closes #152

### CODE REVIEW

**Comment by zach2825** [comment]
@allella, this script can be run on the servers; it should work for any env if deployed through git. 

[scripts/handle-deplopy-update.sh](https://github.com/hackgvl/hackgreenville-com/pull/153/files#diff-e9bda01af011b9d81886750026d118f6892d4773106602d77ab1781ac950a100R1) you can run it like this `./scripts/handle-deplopy-update.sh` if you want. We can maintain that script for any changes so you don't have to guess. 

@oliviasculley I fixed the hg:dev command and added pm2 monit, if you don't like it I can remove it. 
https://github.com/hackgvl/hackgreenville-com/pull/153/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15

I removed an unused blade template and added some documentation linked from the readme.md file. 

I set this to `draft` to encourage any changes if anybody has any.

**Comment by zach2825** [comment]
To be fair, about the image optimization stuff I added. The vite packages and the command I added don't do much, it only saves a few kilobytes, so I removed the packages unless anybody else has a better idea. The ones we serve up now are pretty optimized.

**Comment by allella** [comment]
@zach2825 the mogrify seems to perform less desirable than a couple other image scripts I've used over the years.

The mogrify does make for a smaller JPG, but it's notably blurry, as in the comparison below.

The mogify for PNG takes the [Labs image](https://hackgreenville.com/build/assets/labs-73a1bcb7.png) only dropped by 1KB. The pngquant script below took the original from 546KB to 169KB with no notable distortion.

Here are the commands I've used in years past in production that seem to perform as well or much better than the two proposed mogrify commands.

```

#RECURSIVELY Find JPG files in ALL directory and optimize all of them to keep Google Page Speed Happy skip anything with an improvement of less than 3% (-T3)
find . -type f -name "*.jpg" -exec jpegoptim -m85 -T3 --strip-all {} \;	

# DRY RUN / TEST - Does a RECURSIVE DRY RUN (-n) jpegoptim to see what it would do and skip anything with an improvement of less than 3% (-T3)
find . -type f -name "*.jpg" -exec jpegoptim -m85 -T3 -n --strip-all {} \;	
	
# recursively compress all PNGs in and below the current directory
find . -name '*.png' -exec pngquant --ext .png --quality=65-80 --force --skip-if-larger 256 {} \;	

# optimize all .png files in the current directory. Overwrite the existing file
pngquant --ext=.png --force --skip-if-larger --quality=65-80 *.png	

```

mogrify-text

**Comment by allella** [comment]
Also, the shell script name looks like it has a type scripts/handle-**deplopy**-update.sh

**Comment by zach2825** [comment]
@allella, I updated the script name; thanks for catching that! 

I also updated the image optimization script. It does not substantially change the delivered asset size. The request size went from 3MB to 2.9MB, so that it could have only saved a few kilobytes.

this is the logo.png changes
image

You can see it starts to look washed out. but when viewing it in the browser, it looks fine. I left the images unchanged so we can do optimization tests locally easier. But we should run the optimization script locally and add those changes to the repo

**Comment by allella** [comment]
@zach2825 was the test you shared run with mogrify because I can't produce that with pngquant.  Also, the above shows the PNG was converted to an 8-bit, from 32-bit color, and it looks like some transparency, so that's perhaps part of the washed out issue.

I downloaded https://raw.githubusercontent.com/hackgvl/hackgreenville-com/develop/public/img/logo-v1.png and ran the _pngquant_ command on it and it doesn't have that washed out look. The same test also dropped the image from 43KB to 10KB.  So, I think _pngquant_ is an improvement and has no noticeable difference the test on that PNG file.

pngquant and jpegoptim were what Google Page Speed used to score image compression many years ago. I suspect there would be newer libraries and tooling to do the same, but the manual shell scripts did the trick, so I'm comfortable they are a step in the right direction if the Vite stuff you tried didn't do anything worth the trouble.

Rather than automate the image compression, is there a reminder we can tack on to part of the build or deploy process to remind us / me to manually run the image compression commands from time to time.  Or, if we dev specific commands that can trigger a shell, then perhaps we just run the image optimization as part of some dev process so people don't forget?

**Comment by oliviasculley** [comment]
I think ideally we'd want to use some sort of solution that would be automatically run during the build process and then affect the images included in the build files

**Comment by oliviasculley** [comment]
Something like this looks cool: https://github.com/FatehAK/vite-plugin-image-optimizer

**Comment by allella** [comment]
@oliviasculley yeah, Zach mentioned he tried that Vite package and then reverted it because it didn't do much more than tiny improvements.

It could be those Vite tools need their config tweaked to get noticeable results, but it seems old the defaults wouldn't be decent improvements.  It is possible that I already ran pngquant and jpegoptim on the images Zach was seeing with low improvements.

I did see notable improvements using the command line jpegoptim and pngquant in past projects. Plus, pngquant did good things on the two HG images I tested (as noticed above and below), but I see no reason more modern tools couldn't achieve the same since, so the Vite route seems worth another look for the automation.

The images I used to test happen to be PNGs
https://hackgreenville.com/build/assets/labs-73a1bcb7.png
and
https://raw.githubusercontent.com/hackgvl/hackgreenville-com/develop/public/img/logo-v1.png

so perhaps @zach2825 can see what happens with the Vite with those two files since the other image files could have been previously optimized, and hence the small improvements from Vite.

**Comment by oliviasculley** [comment]
You should be able modify the quality settings in the vite settings which should adjust the filesize when you configure it, maybe I can try playing around with the package

**Comment by zach2825** [comment]
> vite-plugin-image-optimizer

If you don't mind @oliviasculley, please feel free to push any changes to this PR. I did try it maybe miss configured but it did not do much for me. I have no problems with people pushing to my PRs just try to make sure its related changes if possible.

**Comment by zach2825** [comment]
Howdy @allella thats amazing! I want to re-vitit [vite-plugin-image-optimizer](https://github.com/FatehAK/vite-plugin-image-optimizer) if @oliviasculley has some time to give it a try

**Comment by oliviasculley** [comment]
If I get some extra time this week I might end up making a PR targeting your branch. From the docs it looked like you had to set the quality number per filetype but i only just glanced at it for like 30 seconds

**Comment by allella** [comment]
Yeah, it's looks like the Sharp package that used by this Vite package are doing things similar to the tools I was using. 

The [Sharp docs reference jpegotim and pngcrush](https://sharp.pixelplumbing.com/#optimal) (a cousin to pngquant).

It's rather likely I already optimized many of the images in the past, and that's why it didn't look like it was doing much.

The PNG files I mentioned would be decent tests, but also I think this should be an improvement over nothing.

Thanks

**Comment by zach2825** [comment]
I backed out the image optimization stuff I added. It's resolved in this PR https://github.com/hackgvl/hackgreenville-com/pull/155

**Comment by allella** [comment]
@zach2825 this looks straightforward enough for me.

One related question is if we should make a shell script for dev updating too.   That is, mention to run specific scripts in the documentation instead of writing out all of the commands.

I suppose we could still document what specific commands do, but for dev updating and deploying to stage or production it is helpful to be able to point people to run a shell instead of a series of commands. I typically use a shell alias to do the same, but I'm good with shell scripts for the repeatable stuff that will help us avoid people having things break because commands weren't run, or weren't run in the right order.

We have the Docker stuff too, but to some degree the Docker compose files do the repeatable actions. I think if we get the standard commands figured out we can have Olivia make any tweaks or create Docker specific shell commands.

We can create a new issue for this new stuff, but I wanted to ask if it's a good path to follow.

Also, we were talking about this in #148 where Mark has been documenting what commands or scripts to run so we don't have to remember it all.

**Comment by allella** [comment]
@zach2825 this has a couple conflicts since merging in #155.

**Comment by zach2825** [comment]
All resolved @allella thank you

**Comment by allella** [comment]
@zach2825 is there any care for merging this in before #154, or vice versa?

**Pull request merged**
