### PR TITLE
Calendar List View

### PR DESCRIPTION
**Pull request by bogdankharchenko**
Screenshot 2024-04-24 at 10 47 49 AM

### CODE REVIEW

**Comment by allella** [comment]
This sort of begs the question of if we need https://hackgreenville.com/events if we're getting much the same view in this calendar list view.

Thoughts?

**Comment by bogdankharchenko** [comment]
> This sort of begs the question of if we need https://hackgreenville.com/events if we're getting much the same view in this calendar list view.
> 
> Thoughts?

Yeah I asked my self the same question once I made this page.... Benefit of the /events page is google can index this data, whereas this is rendered in Javascript... and doesn't have the same SEO --- not 100% sure of that tho - I am not opposed to remove /events page

**Comment by allella** [comment]
It's a small enough change I guess we'll just see if other come to the conclusion that we don't need /events.

I wouldn't imagine there's not much SEO from the content on these pages for either /calendar or /events given it changes frequently, is short of repetitive content. Though, I wouldn't be surprised if the search engines understood it for what it is, a calendar. 

https://hackgreenville.com/events has the "Add to Calendar" feature and gives us more flexiblity than I'd imagine trying to do the same things within Fullcalendar.

Also, https://hackgreenville.com/events could eventually have rich snippet / semantic markup added if we wanted the search engines to have a better understanding of what's on the page for SEO / search purposes.

It may not be a bad idea to add a rel=canonical on /calendar to give the SEO credibility to /events, since that's going to be the more search engine friendly format.  Though, doing so would likely cause /calendar to not rank as well, since we'd be hinting to the search engines to make its content subordinate to /events.

**Comment by allella** [comment]
Also, there's a merge conflict with the same changes made in #261

**Comment by allella** [comment]
@bogdankharchenko getting the following error on stage when running the deploy shell script.

```
error during build:
Error: [postcss] ENOENT: no such file or directory, open '@fullcalendar/list/main.min.css'
```

**Comment by allella** [comment]
The ENOENT error was resolved by the removal of package-lock.json #270

**Pull request merged**
