### PR TITLE
Add Labs Page

### LINKED ISSUE #138: Add a "Labs" Page
The content of that Labs page will be pulled largely from https://hackgvl.github.io/codeforgreenville.github.io/

Since Zach is [working on some Laravel and layout refresh](https://github.com/hackgvl/hackgreenville-com/issues/136), we should keep that work in mind when adding this new page and navigation items.

### PR DESCRIPTION
**Pull request by oliviasculley**
# Features
This PR adds a page for HackGreenville Labs, see below

Closes #138

# Fixes
- Adds `FORCE_SSL` option to force all urls to be generated with `https`
- Adds yarn to `.tool-versions` for asdf-vm

# Preview

Screenshot 2023-07-09 at 19-29-25 HackGreenville Labs

### CODE REVIEW

**Comment by allella** [comment]
Looks like a good start.

I'd suggest we remove / distance from the word brigade, since that has a lot of CFG baggage.

I'd be okay with removing the 3 projects that are "under consideration" since none have had any real movement in 3+ years and none have a current champion.

Also, if we're going to keep the trolley tracker on there, it would be worth a secondary line acknowledging it was developed by the group formerly know as Code For Greenville.  I didn't do much more than some marketing for that project and we don't have any of the Trolley Tracker team on the current HG Labs crew, so it feels like a stretch to claim it under HG Labs.

Thoughts?

**Comment by oliviasculley** [comment]
I've adjusted the copy, and attached a picture below, but here are some of the other changes:

- Removed "Open Data" from all the APIs to not overwhelm the reader
- Switched up linking to Website/Github to not just only link to Github for all of them :smile:
- Improved spacing for the taglines so word wrapping doesn't make them as confusing

Please let me know any opinions on this! I'm horrible at wording things lol

Screenshot 2023-07-09 at 22-26-11 HackGreenville Labs

**Comment by allella** [comment]
Looks good.

I'll merge this in so we have it to reference at the HG meeting later today.

**Comment by allella** [comment]
On the FORCE_SSL, should we also add that to the .env.example and another of the other .env example files?

**Pull request merged**
