### PR TITLE
Remove Old Pull Event, Pull Orgs commands, and related files

### PR DESCRIPTION
**Pull request by bogdankharchenko**
We no longer need these commands and the associated data files.

### CODE REVIEW

**Comment by allella** [comment]
Duplicate of #200, which has some additional questions about naming consistency and adding descriptions to the task and such.

**Comment by allella** [comment]
Do we have and alternative to the app/Console/Commands/TruncateOrgsAndEvents.php that's been deleted?

I think we used that one after the upgrade, but in the past we've had to use similar commands to purge things to fix bugs.

**Comment by bogdankharchenko** [comment]
> Do we have and alternative to the app/Console/Commands/TruncateOrgsAndEvents.php that's been deleted?
> 
> I think we used that one after the upgrade, but in the past we've had to use similar commands to purge things to fix bugs.

I don't think we will need to do any purging moving forward

**Comment by allella** [comment]
@bogdankharchenko looks like a merge conflict on this PR, so I can't merge it.

Also, #200 had a couple other questions that I figured could be addressed in this PR.

- The _import:events_ doesn't have a description when you run php artisan and it would help.  It would be helpful to add a description since it seems to do more that import events.
- Or, should we consider naming this task import:orgs-and-events since it imports more than just events?
- Do we need the import: prefix or would we prefer to have app:import-orgs-and-events

Thanks

**Comment by bogdankharchenko** [comment]
> @bogdankharchenko looks like a merge conflict on this PR, so I can't merge it.
> 
> Also, #200 had a couple other questions that I figured could be addressed in this PR.
> 
> * The _import:events_ doesn't have a description when you run php artisan and it would help.  It would be helpful to add a description since it seems to do more that import events.
> * Or, should we consider naming this task import:orgs-and-events since it imports more than just events?
> * Do we need the import: prefix or would we prefer to have app:import-orgs-and-events
> 
> Thanks

1. I will add a description and resolve conflicts.
2. We no longer will import Organizations - since they now live this project/database.
3. I'm personally a fan of easy commands: `import:events` seems like a good choice for me, but I'm not married to it.

Let me know if you have any other questions

**Pull request merged**
