### PR TITLE
HG-133 - use pint and prettier to format the codebase

### LINKED ISSUE #133: Add the pint linter to the code to help standardise the code
Also running the upgrade on yarn and composer

### PR DESCRIPTION
**Pull request by zach2825**
closes #133

### CODE REVIEW

**Comment by oliviasculley** [comment]
Looks great! I'd like to see this in soon to make https://github.com/hackgvl/hackgreenville-com/pull/137 a bit more reviewable :+1:

**Review by oliviasculley — APPROVED** [review]

**Comment by allella** [comment]
Above my pay grade. I'm assuming this is making spaces and such consistent?

**Review by allella — APPROVED** [review]

**Comment by allella** [comment]
Yeah, is this going to create 80 problems when another branch with the old formatting is merged in?

**Comment by zach2825** [comment]
Hey @allella 

I don't think we have old unmerged branches, But resolving those conflicts are easy. When ready, the dev would accept their own changes and re-run `yarn lint:php,` and it would re-fix the code. 

I used laravel pint and Prettier to format the code. It is just changing " to ' and converting 1 line functions to PHP arrow methods and formatted markdown files [like here](https://github.com/hackgvl/hackgreenville-com/pull/134/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R23)

I aim to make the codebase more readable and easier to contribute to.

**Comment by allella** [comment]
@zach2825 is this ready to merge?

**Comment by zach2825** [comment]
Yes

**Comment by allella** [comment]
Alright, this has been merged. Since it was just syntax I don't see where / how it would break anything and the stage site is good
https://stage.hackgreenville.com/

**Pull request merged**
