### PR TITLE
Sanitize HTML in Event Descriptions

### PR DESCRIPTION
**Pull request by ThorntonMatthewD**
# WIP
Adds the [mews/purifier](https://github.com/mewebstudio/Purifier) package as a depdency and utilizes it to sanitize HTML contained in event descriptions prior to persisting them.

Screenshot_2023-12-10_21-55-44

### CODE REVIEW

**Comment by allella** [comment]
@ThorntonMatthewD is there a configuration file that's being set for this package? If so, would we want to add something to the .env.example or some other place so we know what the config should look like?

**Comment by ThorntonMatthewD** [comment]
@allella So far I've just been tinkering with the default config that the package ships with. We could specify a custom config at `config/purifier.php` if the need arises, but I've not done enough testing to determine if that is something that should be pursued.

**Comment by allella** [comment]
Sounds good.

**Comment by bogdankharchenko** [comment]
@ThorntonMatthewD let's get this merged in

**Comment by bogdankharchenko** [comment]
@ThorntonMatthewD Can we get this merged in? =)

**Comment by allella** [comment]
@bogdankharchenko did we address this in another way?

The HTML in the Slackbot in #events does some goofy stuff, but that's [perhaps a problem to be solved in that repo](https://github.com/hackgvl/slack-events-bot/issues/16).

**Comment by bogdankharchenko** [comment]
I will solve it another way

**Pull request closed without merging**
