### PR TITLE
Image Optimization with Vite

### PR DESCRIPTION
**Pull request by bogdankharchenko**
This is a take on part of the PR https://github.com/hackgvl/hackgreenville-com/pull/153 which Zach worked on.

This will allow us to optimize images by just running `yarn run build` without having to execute any other commands.
Screenshot 2023-07-24 at 4 35 58 PM

### CODE REVIEW

**Comment by oliviasculley** [comment]
This one looks fantastic! Thanks for getting this working!

The only issue that I can see is that this PR introduces `package.lock` from using npm, but also updates `yarn.lock`. We should ideally only have one of these to avoid them conflicting with each other, but if `package.lock` is removed then the rest looks amazing!

**Comment by bogdankharchenko** [comment]
> This one looks fantastic! Thanks for getting this working!
> 
> The only issue that I can see is that this PR introduces `package.lock` from using npm, but also updates `yarn.lock`. We should ideally only have one of these to avoid them conflicting with each other, but if `package.lock` is removed then the rest looks amazing!

Good call! Done.

**Comment by allella** [comment]
Nice. I don't see any showstoppers on this and can merge and test on stage if @zach2825 is good with it.

Do we need to worry about merging in this before other PRs, or vice versa?

**Comment by zach2825** [comment]
Sorry, I don't know why I didn't see this. Lol, well done :1st_place_medal:  @allella

**Review by zach2825 — APPROVED** [review]
:fireworks:

**Pull request merged**
