### PR TITLE
Document FORCE_SSL in environment .env files

### PR DESCRIPTION
**Pull request by MarkMcDaniels**
Added FORCE_SSL to '.env.testing' and '.env.docker' in response @allella #150 .

### CODE REVIEW

**Comment by allella** [comment]
I think that's right, but asking Olivia to review it too.

Thanks

**Comment by allella** [comment]
@MarkMcDaniels as a more general note, this PR looks like it was pushed to your develop branch. I see you previously created new branches, so I assume this was just an oversight.

It can cause merge conflicts to commit directly to your develop. There are commands to sync up with the upstream and overwrite your develop, so not a huge deal, but the unique branches for each PR do help avoid problems when changes are delayed getting merged in or when other changes merge into develop while your PR is waiting to be merged.

Also, the title or the PR could / should be descriptive.

**Comment by oliviasculley** [comment]
Thanks for picking this up Mark!

While the changes look good so far, I think we'll want to add this to `.env.example` as well. In addition, these changes are probably small enough so they can all be combined into one commit, but having them split up into separate commits isn't a show stopper. Once it's added to `.env.example`, it should be ready to go!

**Comment by allella** [comment]
Also, @MarkMcDaniels if you put
Closes #150 in the PR post it will auto-close the issue when the PR is closed.

You did put #150 but I think you have to put "closes" before it for the auto-close to work.

**Comment by MarkMcDaniels** [comment]
Sorry, I'm still learning. Almost everything I do is by myself. Thanks for
being patient while I figure it out.

**Comment by allella** [comment]
Not a problem @MarkMcDaniels. We're all learning, so don't be shy to give us tips too.

**Comment by zach2825** [comment]
If you don't mind could you make the title of this PR more meaningful? The code changes may not be necessary since false is assumed in this scenario, but showing these settings in the .env.example file is an amazing way to add self-documenting stuff. On that note, if you'd like to add some commenting around those settings to explain what they do, I would not be against it :+1:

**Comment by allella** [comment]
@MarkMcDaniels I think if the FORCE_SSL is added to .env.example is the only thing holding up this PR from a merge.

Zach's suggestion to add comments to the .env files would be helpful, because I honestly don't know what some of the variables are doing, but we can open a new PR on that since it could be a more expansive task.

**Pull request merged**
