### PR TITLE
Add GitHub Action to run unit tests

### PR DESCRIPTION
**Pull request by irby**
Addresses #157, adds a GitHub Actions workflow to run unit tests when changes to code occurs.

### CODE REVIEW

**Comment by bogdankharchenko** [comment]
@allella I think you may be the only one who can see if this works - since non-repo managers are not allowed to add/edit github actions files.

**Comment by allella** [comment]
Is this a merge and find out how it works situation, or is there a way to test before merging?

**Comment by irby** [comment]
@allella I think you should be able to test it out before merging. I have a PR for my own forked repo and was able to run the workflow. I think, by default, GitHub will not run new workflows without approval. Can you check to see if there's a pending workflow in the Actions section?

image

**Comment by allella** [comment]
[Step 5 of the GitHub docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) suggests I should see a 

> "Workflow(s) awaiting approval", click Approve and run.

I don't see that.

I'm not worried about merging this workflow, but I am curious of the process for testing future ones before merging.

**Review by allella — APPROVED** [review]

**Review by allella — APPROVED** [review]

**Review by allella — APPROVED** [review]

**Pull request merged**
