### PR TITLE
Add RefactorGVL text and links

### LINKED ISSUE #224: Add RefactorGVL Links to the Footer and About Page
Now that HG is an initiative of https://refactorgvl.com/ we could add something like

_HackGreenville is a program of the [RefactorGVL](https://refactorgvl.com/)_ non-profit.

to the footer and somewhere in the [About page](https://hackgreenville.com/about) / history.

### PR DESCRIPTION
**Pull request by JSn1nj4**
This adds RefactorGVL text and links to the About page and footer.

Closes #224

### CODE REVIEW

**Comment by JSn1nj4** [comment]
@allella If HackGreenville is a program of RefactorGVL now, does that mean the copyright should be RefactorGVL's?
(Sorry, I figured this PR would be the more appropriate place than the issue for follow-up questions, so I moved it here.)

**Comment by allella** [comment]
At least for now, any licenses or copyright would be in the name of HackGreenville

image

**Comment by JSn1nj4** [comment]
@allella I left copyright in the name of HackGreenville and just added the requested text as another sentence.
image

Also added the requested paragraph to the About page.

**Comment by JSn1nj4** [comment]
@allella fixed the text as requested

**Review by allella — APPROVED** [review]

**Pull request merged**
