### PR TITLE
Remove php artisan migrate --seed from composer.json

### PR DESCRIPTION
**Pull request by irby**
Addresses issue identified in #158 , remove migration script from post-install step of `composer install`.

### CODE REVIEW

**Comment by bogdankharchenko** [comment]
I can't officially review PR's here, but @allella  this looks good to me.

**Review by zach2825 — APPROVED** [review]
Nice and easy :fire_extinguisher:

**Review by bogdankharchenko — APPROVED** [review]

**Comment by allella** [comment]
Alright, so we're removing it. Do we need to update the CONTRIBUTING.md to remind the Docker folks to run the migration, or is something in the most recent docs changes already handling that migration step for Docker folks?

**Comment by irby** [comment]
> Alright, so we're removing it. Do we need to update the CONTRIBUTING.md to remind the Docker folks to run the migration, or is something in the most recent docs changes already handling that migration step for Docker folks?

@allella yes, I think the documentation needs to be updated to reflect that running `composer install` does not automatically run the migrations. Good catch.

**Comment by allella** [comment]
Thanks @irby

I guess feel free to add what's necessary to the CONTRIBUTING.md.

This involves Docker, so added Olivia as a reviewer.

**Comment by allella** [comment]
@irby https://github.com/hackgvl/hackgreenville-com/issues/142 is operating in/around the same part of the docs.

We were waiting on #153 to update the "Host" side to add more to https://github.com/hackgvl/hackgreenville-com/pull/148

I just merged #153 in, so if you want to update the "Host" section of the docs to say to run scripts/update-deploy.sh in the appropriate section, instead of the individual commands, then that might close #142 and supersede #148

**Review by oliviasculley — APPROVED** [review]
This all looks great!

**Comment by allella** [comment]
@all-contributors add @irby for code, review, bug, test

**Pull request merged**
