### PR TITLE
Add Women Who Code & Agile Learning Institute to Give page

### LINKED ISSUE #228: List 2 more orgs on Give page
@ChristinaDRoberts asked if we could list these 2 orgs on the Give page:
- [Women Who Code Greenville][wwcg]
- Agile Learning Institute ([mentor][ali_mentor]) ([donate][ali_donate])

[wwcg]: https://opencollective.com/wwcodegreenville
[ali_donate]: https://agile-learning.institute/donate
[ali_mentor]: https://agile-learning.institute/become-a-mentor

I'm following up for small text snippets in case there's anything specific we should say, or asking if it's fine if we borrow a bit of text from those sites instead.

----
As an side, once #210 is finished, managing the Give content via the admin panel can be implemented pretty easily as well.

### PR DESCRIPTION
**Pull request by JSn1nj4**
Closes #228

### CODE REVIEW

**Review by ThorntonMatthewD — APPROVED** [review]

**Comment by allella** [comment]
Adding a couple groups to the page is not an immediate concern, but it does show the point that over time we'd likely have a bigger and noisy page.

One thought that both I and some HG Committee folks mentioned was perhaps adding "Give" and "Volunteer" links to the orgs API.  This could be after it's migrated from Drupal to Laravel.

Then, we could highlight the orgs in the Orgs page with icons showing which groups have opportunities to contribute.

This wouldn't necessarily replace the "Give" page, but it may allow us to highlight the needs on the Orgs page and had a similar, database-driven list view on the "Give" page for those orgs which have these specific needs.

In any case, this HTML page is a good "get it done on paper" and will likely serve for the near term goal, so thanks for making it real.

We can figure out if/how to blend the giving / volunteering stuff into the orgs model after the migration from Drupal to Laravel.

**Comment by allella** [comment]
The only other thought on the Give page is how we're sorting the orgs.

The "Donate" section is alphabetical, but the "Volunteer" section is not.  

This is only mildly a concern because it's unclear if we're prioritizing groups or displaying them in an alphabetical list.

If we're prioritizing, then I'd thing RefactorGVL and HackGreenville would be at the "top-left". 

Though, I don't think we really need to get into the business of prioritizing, so things could be easier if we just made the alphabetical so there's no "why did they put that group before our group".

**Comment by JSn1nj4** [comment]
Points noted on the page potentially growing quite big. If I'm asked about adding more in the future, I'll forward the request along first to help discuss how we might keep things tidy and such.

I'll also alphabetize tonight.

**Comment by JSn1nj4** [comment]
@allella I reorganized them as requested.

## Donate
image

## Volunteer
image

**Pull request merged**
