### PR TITLE
Using `glhd/airephp` as a form builder instead of `laravelcollective/html`

### PR DESCRIPTION
**Pull request by bogdankharchenko**
#180 this is a take on this issue - which replaces the laravelcollective/html package - with glhd/aire-bootstrap - this does the same thing as the laravel collective package, but looks a lot cleaner.

### New Code
Screenshot 2023-10-19 at 2 31 58 PM

### CODE REVIEW

**Comment by bogdankharchenko** [comment]
This only changes the contact form - the sign-up form is the other place which will need to be updated. If this is approved, I will make changes there too.

**Comment by oliviasculley** [comment]
I'm a bit lazy and haven't previewed these changes, but just reading about `aire` seems to imply that it uses tailwind classes by default, and I'm not sure if it'd work since I don't think that tailwind is set up in this project. While the fix is probably just specifying the bootstrap classes manually, I wouldn't mind switching to bootstrap to tailwind :)

**Comment by ThorntonMatthewD** [comment]
It looks like they have a Bootstrap theme available: https://airephp.com/bootstrap

**Comment by bogdankharchenko** [comment]
Aire allows the templating, it's currently using (in this demo) bootstrap theme but if we ever decide to twice to tailwind it's an easy transition.

**Review by allella — APPROVED** [review]

**Comment by bogdankharchenko** [comment]
@allella merge it!

**Pull request merged**
