### PR TITLE
HG-135 - upgrades

### LINKED ISSUE #135: Upgrade to laravel 10 and replace mix with vite
Vite builds and dev start is substantially faster and more minimized than webpack, and vite has a cleaner and easier-to-read config file. 

And laravel has passed version 10; we're still on 8.

### PR DESCRIPTION
**Pull request by zach2825**
- [x] cleanout old vue components deps and code
- [x] fix homepage timeline read more button. They can't use sweatalert anymore, I converted the component over to use alpine, I think alpine has a modal component that can be used in its place. 
image

Closes #135

### CODE REVIEW

**Comment by zach2825** [comment]
livewire modals - https://github.com/wire-elements/modal

**Comment by allella** [comment]
@zach2825 if this is ready to merge, then please let me know what commands to run to avoid blowing things up.

We still have https://stage.hackgreenville.com so it will be deployed there first to test.

**Comment by allella** [comment]
Sorry, I see this is the one you said was not ready.  

Could you post any deploy commands on the other PRs that are ready so I can pull them to stage and run the commands and check that things are good before doing the same on the live site?

**Comment by zach2825** [comment]
All resolved @allella

**Comment by zach2825** [comment]
I can't remember the current process to deploy these changes. 

Deploys now should do these:
- `yarn install`
- `composer install`
- `yarn build`

**Comment by allella** [comment]
@zach2825 this is showing conflicts too.

Please let me know if you when you want to merge this and if we should go live with the previous two PRs now, or merge all PRs, test, and go live in one shot.

Thanks

**Comment by zach2825** [comment]
@allella, sorry about that; all resolved should not happen going forward. These few PRs contained a lot of changes that depended on each other.

**Review by allella — APPROVED** [review]

**Comment by allella** [comment]
@zach2825 I'm about to merge this into the _develop_ branch and test on stage.

On the stage server, should I run all of the following?

yarn install
composer install
yarn build

Also, it looks like there's are two new VITE  .env variables I need to copy from .env.example, correct?

**Comment by zach2825** [comment]
Hey @allella,

No, you should not need those. Those variables changed for vite, so I wanted to update them so if anybody wants to use them in the future, they will be more accurate. They are just for push notifications using web sockets.

**Comment by allella** [comment]
@zach2825 I merged in and pulled the code to [stage](https://stage.hackgreenville.com/) and it's not surprisingly needing more commands.

You said in the last message I didn't need to run yarn or composer commands, but it seems like something is needed to get all the Laravel 10 updates and clearing out old gunk.  What's the proper order of commands for getting this up to snuff on the stage site?

I did try php artisan view:cache but I'm assuming a yarn or composer command needs to be run at least for this upgrade, but I'd rather not keep guessing and mess things up.

**Comment by allella** [comment]
Also,

**Comment by allella** [comment]
@zach2825 nevermind, I see you were telling me I don't need the VITE vars and I read it quickly to mean that the commands above weren't needed.

I ran the three commands on stage and it's unbroken.
https://stage.hackgreenville.com

Are the three yarn and composer commands something we should always run on deploys? If so, shall we add these do the README?

**Comment by allella** [comment]
PRs #139 #137 and #134 are now live. Thanks @zach2825

**Pull request merged**
